import type { WorkItem } from "./work-item";

export const MOCK_WORK_ITEMS: WorkItem[] = [
  {
    id: "task-1",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    title: "Concrete pouring – North Wing slab",
    description: "Pour and cure ground floor slab for Zone A North Wing.",
    status: "in_progress",
    priority: "high",
    assignedTo: "user-101",
    dueDate: new Date("2024-03-15"),
    progress: 60,
    progressPercent: 60,
    metadata: {},
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "task-2",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    title: "Formwork installation – North Wing",
    description: "Install timber formwork ahead of concrete pour.",
    status: "completed",
    priority: "high",
    assignedTo: "user-102",
    dueDate: new Date("2024-02-28"),
    progress: 100,
    progressPercent: 100,
    metadata: {},
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-02-28"),
  },
  {
    id: "task-3",
    projectId: "project-1",
    spatialNodeId: "zone-2",
    title: "Electrical conduit installation – South Wing",
    description: "Run conduit through walls and ceilings per drawing E-201.",
    status: "planned",
    priority: "medium",
    assignedTo: "user-103",
    dueDate: new Date("2024-04-01"),
    progress: 0,
    progressPercent: 0,
    metadata: {},
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "task-4",
    projectId: "project-1",
    spatialNodeId: "zone-2",
    title: "Waterproofing membrane – South Wing basement",
    description: "Apply waterproofing membrane to basement walls.",
    status: "blocked",
    priority: "critical",
    assignedTo: "user-104",
    dueDate: new Date("2024-03-10"),
    progress: 20,
    progressPercent: 20,
    metadata: { blockedReason: "Material delivery delayed" },
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-18"),
  },
  {
    id: "task-5",
    projectId: "project-1",
    spatialNodeId: "zone-3",
    title: "Steel reinforcement – East Block columns",
    description: "Place and tie rebar for 8 columns in Zone C.",
    status: "in_progress",
    priority: "high",
    assignedTo: "user-101",
    dueDate: new Date("2024-03-20"),
    progress: 40,
    progressPercent: 40,
    metadata: {},
    createdAt: new Date("2024-02-12"),
    updatedAt: new Date("2024-02-22"),
  },
];
