import type { TimelineEvent } from "./timeline-event";
import type { ProgressRecord } from "./progress-record";

export const MOCK_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: "ev-tl-1",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    type: "construction_start",
    title: "Construction start – North Wing",
    description: "Ground-breaking and mobilisation commenced for North Wing.",
    timestamp: new Date("2024-01-15T08:00:00"),
    metadata: {},
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "ev-tl-2",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    type: "inspection",
    title: "Structural inspection – North Wing",
    description: "First structural inspection completed. Minor issues noted.",
    timestamp: new Date("2024-02-16T10:00:00"),
    metadata: { inspectionId: "insp-1" },
    createdAt: new Date("2024-02-16"),
    updatedAt: new Date("2024-02-16"),
  },
  {
    id: "ev-tl-3",
    projectId: "project-1",
    spatialNodeId: "zone-2",
    type: "inspection",
    title: "Waterproofing inspection – South Wing",
    description: "Membrane application inspection in progress.",
    timestamp: new Date("2024-02-20T14:00:00"),
    metadata: { inspectionId: "insp-2" },
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "ev-tl-4",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    type: "defect_created",
    title: "Defect raised – Honeycomb in column C2",
    description: "NCR issued for honeycomb void on column C2.",
    timestamp: new Date("2024-02-16T11:30:00"),
    metadata: { defectId: "defect-1" },
    createdAt: new Date("2024-02-16"),
    updatedAt: new Date("2024-02-16"),
  },
  {
    id: "ev-tl-5",
    projectId: "project-1",
    spatialNodeId: "zone-2",
    type: "defect_created",
    title: "Defect raised – Waterproofing gap south wall",
    description: "Critical gap in membrane at wall/floor junction.",
    timestamp: new Date("2024-02-20T15:00:00"),
    metadata: { defectId: "defect-3" },
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "ev-tl-6",
    projectId: "project-1",
    spatialNodeId: "zone-2",
    type: "defect_resolved",
    title: "Defect resolved – Surface rust on rebar",
    description: "Rebar surface rust treated and verified. Defect closed.",
    timestamp: new Date("2024-02-24T09:00:00"),
    metadata: { defectId: "defect-4" },
    createdAt: new Date("2024-02-24"),
    updatedAt: new Date("2024-02-24"),
  },
  {
    id: "ev-tl-7",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    type: "milestone",
    title: "Milestone – North Wing slab pour complete",
    description: "Concrete pour for ground floor slab finished and curing.",
    timestamp: new Date("2024-03-01T17:00:00"),
    metadata: {},
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
];

export const MOCK_PROGRESS_RECORDS: ProgressRecord[] = [
  {
    id: "pr-1",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    progressPercent: 10,
    status: "in_progress",
    recordedAt: new Date("2024-01-20"),
    recordedBy: "user-101",
    metadata: {},
  },
  {
    id: "pr-2",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    progressPercent: 40,
    status: "in_progress",
    recordedAt: new Date("2024-02-05"),
    recordedBy: "user-101",
    metadata: {},
  },
  {
    id: "pr-3",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    progressPercent: 75,
    status: "in_progress",
    recordedAt: new Date("2024-02-20"),
    recordedBy: "user-101",
    metadata: {},
  },
  {
    id: "pr-4",
    projectId: "project-1",
    spatialNodeId: "zone-2",
    progressPercent: 0,
    status: "not_started",
    recordedAt: new Date("2024-01-20"),
    recordedBy: "user-102",
    metadata: {},
  },
  {
    id: "pr-5",
    projectId: "project-1",
    spatialNodeId: "zone-2",
    progressPercent: 20,
    status: "blocked",
    recordedAt: new Date("2024-02-18"),
    recordedBy: "user-102",
    metadata: { blockedReason: "Material delivery delayed" },
  },
  {
    id: "pr-6",
    projectId: "project-1",
    spatialNodeId: "zone-3",
    progressPercent: 40,
    status: "in_progress",
    recordedAt: new Date("2024-02-22"),
    recordedBy: "user-103",
    metadata: {},
  },
];
