import type { Inspection } from "./inspection";
import type { Defect } from "./defect";
import type { CorrectiveAction } from "./corrective-action";

export const MOCK_CORRECTIVE_ACTIONS: CorrectiveAction[] = [];

export const MOCK_INSPECTIONS: Inspection[] = [
  {
    id: "insp-1",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    title: "Structural Inspection – North Wing",
    description: "Check concrete pour quality and rebar placement.",
    status: "completed",
    inspectionType: "structural",
    result: "fail",
    assignedTo: "user-201",
    scheduledDate: new Date("2024-02-15"),
    inspectedDate: new Date("2024-02-16"),
    completedDate: new Date("2024-02-16"),
    metadata: {},
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-16"),
  },
  {
    id: "insp-2",
    projectId: "project-1",
    spatialNodeId: "zone-2",
    title: "Waterproofing Inspection – South Wing",
    description: "Verify membrane application coverage and joints.",
    status: "in_progress",
    inspectionType: "waterproofing",
    result: null,
    assignedTo: "user-202",
    scheduledDate: new Date("2024-02-20"),
    inspectedDate: null,
    completedDate: null,
    metadata: {},
    createdAt: new Date("2024-02-12"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "insp-3",
    projectId: "project-1",
    spatialNodeId: "zone-3",
    title: "Steel Inspection – East Block",
    description: "Inspect rebar sizes, spacing, and tie wire.",
    status: "scheduled",
    inspectionType: "structural",
    result: null,
    assignedTo: "user-201",
    scheduledDate: new Date("2024-03-05"),
    inspectedDate: null,
    completedDate: null,
    metadata: {},
    createdAt: new Date("2024-02-22"),
    updatedAt: new Date("2024-02-22"),
  },
];

export const MOCK_DEFECTS: Defect[] = [
  {
    id: "defect-1",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    inspectionId: "insp-1",
    title: "Honeycomb in column C2",
    description: "Void area visible on column C2 surface after formwork removal.",
    severity: "high",
    status: "open",
    assignedTo: "user-101",
    dueDate: new Date("2024-03-01"),
    closedAt: null,
    locationLng: 100.4992,
    locationLat: 13.7572,
    metadata: {},
    createdAt: new Date("2024-02-16"),
    updatedAt: new Date("2024-02-16"),
  },
  {
    id: "defect-2",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    inspectionId: "insp-1",
    title: "Crack in slab – grid B3",
    description: "Hairline crack 1.2m long at grid intersection B3.",
    severity: "medium",
    status: "in_progress",
    assignedTo: "user-102",
    dueDate: new Date("2024-03-10"),
    closedAt: null,
    locationLng: 100.5005,
    locationLat: 13.7565,
    metadata: {},
    createdAt: new Date("2024-02-16"),
    updatedAt: new Date("2024-02-18"),
  },
  {
    id: "defect-3",
    projectId: "project-1",
    spatialNodeId: "zone-2",
    inspectionId: "insp-2",
    title: "Waterproofing membrane gap – south wall",
    description: "Membrane not lapped correctly at wall/floor junction.",
    severity: "critical",
    status: "open",
    assignedTo: "user-103",
    dueDate: new Date("2024-02-28"),
    closedAt: null,
    locationLng: 100.4988,
    locationLat: 13.7542,
    metadata: { blockedBy: "material shortage" },
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "defect-4",
    projectId: "project-1",
    spatialNodeId: "zone-2",
    inspectionId: "insp-2",
    title: "Surface rust on rebar – basement",
    description: "Exposed rebar showing surface rust before concrete pour.",
    severity: "low",
    status: "resolved",
    assignedTo: "user-104",
    dueDate: new Date("2024-02-25"),
    closedAt: null,
    locationLng: 100.5012,
    locationLat: 13.7548,
    metadata: {},
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-24"),
  },
  {
    id: "defect-5",
    projectId: "project-1",
    spatialNodeId: "zone-3",
    inspectionId: null,
    title: "Missing stirrups – column D4",
    description: "Column D4 missing 3 stirrups per drawing S-301.",
    severity: "critical",
    status: "open",
    assignedTo: "user-101",
    dueDate: new Date("2024-03-08"),
    closedAt: null,
    locationLng: 100.5040,
    locationLat: 13.7560,
    metadata: {},
    createdAt: new Date("2024-02-23"),
    updatedAt: new Date("2024-02-23"),
  },
];
