import type { Evidence } from "./evidence";

export const MOCK_EVIDENCE: Evidence[] = [
  {
    id: "ev-1",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    workItemId: "task-1",
    defectId: null,
    type: "photo",
    title: "Concrete pour – North Wing slab",
    description: "Progress photo of concrete pour at grid A1-B3.",
    fileUrl: "https://example.com/evidence/ev-1.jpg",
    thumbnailUrl: "https://example.com/evidence/ev-1-thumb.jpg",
    locationLng: 100.4993,
    locationLat: 13.7571,
    capturedBy: "user-101",
    capturedAt: new Date("2024-02-20T08:30:00"),
    metadata: {},
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "ev-2",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    workItemId: null,
    defectId: "defect-1",
    type: "photo",
    title: "Honeycomb defect – column C2",
    description: "Close-up of honeycomb void on column C2 surface.",
    fileUrl: "https://example.com/evidence/ev-2.jpg",
    thumbnailUrl: "https://example.com/evidence/ev-2-thumb.jpg",
    locationLng: 100.4991,
    locationLat: 13.7573,
    capturedBy: "user-201",
    capturedAt: new Date("2024-02-16T10:15:00"),
    metadata: {},
    createdAt: new Date("2024-02-16"),
    updatedAt: new Date("2024-02-16"),
  },
  {
    id: "ev-3",
    projectId: "project-1",
    spatialNodeId: "zone-2",
    workItemId: null,
    defectId: "defect-3",
    type: "video",
    title: "Waterproofing inspection walkthrough – South Wing",
    description: "Video walkthrough of membrane application on south wall.",
    fileUrl: "https://example.com/evidence/ev-3.mp4",
    thumbnailUrl: "https://example.com/evidence/ev-3-thumb.jpg",
    locationLng: 100.4987,
    locationLat: 13.7543,
    capturedBy: "user-202",
    capturedAt: new Date("2024-02-20T14:00:00"),
    metadata: { durationSeconds: 142 },
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
  {
    id: "ev-4",
    projectId: "project-1",
    spatialNodeId: "zone-2",
    workItemId: "task-3",
    defectId: null,
    type: "document",
    title: "Electrical drawing E-201",
    description: "Approved IFC drawing for South Wing electrical conduit routing.",
    fileUrl: "https://example.com/evidence/ev-4.pdf",
    thumbnailUrl: null,
    locationLng: 100.5010,
    locationLat: 13.7549,
    capturedBy: "user-103",
    capturedAt: new Date("2024-02-10T09:00:00"),
    metadata: { pageCount: 4, revision: "C" },
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "ev-5",
    projectId: "project-1",
    spatialNodeId: "zone-3",
    workItemId: "task-5",
    defectId: "defect-5",
    type: "photo",
    title: "Missing stirrups – column D4",
    description: "Photo evidence of missing stirrups per NCR-0042.",
    fileUrl: "https://example.com/evidence/ev-5.jpg",
    thumbnailUrl: "https://example.com/evidence/ev-5-thumb.jpg",
    locationLng: 100.5041,
    locationLat: 13.7559,
    capturedBy: "user-101",
    capturedAt: new Date("2024-02-23T11:00:00"),
    metadata: {},
    createdAt: new Date("2024-02-23"),
    updatedAt: new Date("2024-02-23"),
  },
  {
    id: "ev-6",
    projectId: "project-1",
    spatialNodeId: "zone-1",
    workItemId: null,
    defectId: null,
    type: "document",
    title: "Structural inspection report – North Wing",
    description: "Signed inspection report from insp-1.",
    fileUrl: "https://example.com/evidence/ev-6.pdf",
    thumbnailUrl: null,
    locationLng: 100.5001,
    locationLat: 13.7567,
    capturedBy: "user-201",
    capturedAt: new Date("2024-02-16T17:00:00"),
    metadata: { pageCount: 12 },
    createdAt: new Date("2024-02-16"),
    updatedAt: new Date("2024-02-16"),
  },
];
